name: Deploy Employee Portal

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/employee-portal

            git pull

            sudo docker stop employee-app || true
            sudo docker rm employee-app || true

            sudo docker build -t employee-portal:v1 .

            sudo docker run -d \
              -p 5000:5000 \
              --name employee-app \
              employee-portal:v1